### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by HereIsKevin** [ashmail/ashmail#1]
AshMail sends emails one-by-one. On a small scale, this is acceptable, but for anything more than 100 emails, this is way too slow. Instead of blocking for each email, it is better to send multiple emails concurrently. Otherwise, **AshMail is too slow to be of any use except for sending emails to friends**.

**Comment by 0x44RU5H** [comment]
Interesting. Do you think adding threading would make it faster?

**Comment by 0x44RU5H** [comment]
Threading added in b6f8b78

**Comment by HereIsKevin** [comment]
By creating one thread for each email all at the same time, this approach runs into serious resource usage problems. Each thread takes up around 1 MB of RAM for its stack. As a result, when sending 10000 emails, this is going to take at least 10 GB of RAM. Instead of using `threading`, use `concurrent.futures`, which manages a thread pool for you, or even better, `asyncio` with [`aiosmtpd`](https://aiosmtpd.readthedocs.io/en/latest/).

**Comment by 0x44RU5H** [comment]
Through my testing, creating a thread for one million emails takes up about 3 GB of RAM. It is not RAM intensive, but is CPU intensive. It causes four out of a six core CPU to run at about 100% for the aforementioned test.

**Comment by HereIsKevin** [comment]
I never really tested, as I am just going on what I know. Still, it is better to use `concurrent.futures` just for the sake of having a much simpler API.

**Comment by 0x44RU5H** [comment]
Nice!
